// src/shared/constants/messages.ts
export const Messages = {
  AUTH: {
    LOGIN_SUCCESS: "Login Success",
    LOGIN_EXPIRED: "Login expired",
    UNAUTHORIZED: "Unauthorized access",
    INVALID_TOKEN: "Invalid or expired token",
    INVALID_OTP_PURPOSE: "Invalid OTP purpose",
    COMPANY_PENDING: "Company not verified. Please wait for admin approval",
    ACCOUNT_NOT_FOUND: "No account found for this email",
    EMAIL_EXPIRED_REDIS: "User data expired or not found in Redis",
    ADMIN_LOGIN_SUCCESS: "Admin login successful",
    OTP_SUCCESS: "OTP sent to your registered email.",
    GOOGLE_USER: "This email is registered via Google Sign-In. No password reset required.",
    OTP_RESEND_SUCCESS: "OTP resent successfully. Please check your email.",
    PASSWORD_RESET_SUCCESS: "Password has been reset successfully.",
    PASSWORD_RESET_EXPIRED: "Password reset session expired",
    OTP_GENERATE_SUCCESS: "OTP generated and sent successfully",
    OTP_VERIFY_SUCCESS: "OTP verified successfully",
    AUTH_FAILED: "Authentication failed",
    ACCOUNT_BLOCKED: "Your account has been blocked. Please contact admin.",
    GOOGLE_USER_LOGIN: "This email is registered via Google Sign-In. No password reset required.",
    NO_PASSWORD: "Password is not available for this account. Please contact the administrator or use the forgot password option.",
    PASSWORD_REQUIRED: "Password required",
    LOGOUT_SUCCESS: "Logged out successfully",
    INVALID_ROLE_REPO: "Invalid role or repository",
    EMAIL_ALREADY_IN_USE: "Email already in use",
    EMAIL_REGISTERED_WITH_GOOGLE: "EMAIL_REGISTERED_WITH_GOOGLE",
    EMAIL_REGISTERED_AS_COMPANY: "Email is already registered as company",
    EMAIL_REGISTERED_AS_USER: "Email is already registered as user",
    INVALID_CREDENTIALS: "Invalid email or password",
    ACCESS_DENIED: "Access Denied. User role not found.",
    ROLE_NOT_FOUND: "Access Denied. Your role is not authorized.",
  },
  
  USER: {
    NOT_FOUND: "User not found",
    BANNED: "This account is banned",
    USERSEARCH_SUCCESS: "Users fetched successfully",
    PROFILE_UPDATE_SUCCESS: "Profile updated successfully",
    PROFILE_UPDATE_FAILED: "Failed to update profile",
    PROFILE_FETCH_SUCCESS: "Profile fetched successfully",
    USER_ID_REQUIRED: "User ID is required",
    PROFILE_IMAGE_UPLOAD_SUCCESS: "Profile image uploaded",
    FIELD_REQUIRED: "Field name required",
    CANNOT_DELETE_FIELD: "Cannot delete this field",
    FIELD_DELETE_SUCCESS: "Field deleted successfully",
    INVALID_DATA: "Invalid data",
    FAVOURITES_UPDATE_SUCCESS: "Favourites updated",
    FAVOURITES_FETCH_SUCCESS: "Favourites fetched",
    PASSWORD_CHANGE_SUCCESS: "Password changed successfully",
    COMPANIES_NO_FAVOURITES: "Companies cannot add favourites",
  },

  COMPANY: {
    NOT_FOUND: "Company not found",
    DOCUMENTS_REQUIRED: "Exactly 3 documents are required",
    UPLOAD_SUCCESS: "Documents uploaded successfully. Await admin approval.",
    PROFILE_UPDATE_SUCCESS: "Company profile updated successfully",
    IMAGE_UPLOAD_SUCCESS: "Profile image uploaded successfully",
    ID_REQUIRED: "Company ID is required",
    PROFILE_DATA_REQUIRED: "Company ID and Profile Data are required",
    IMAGE_REQUIRED: "No image file provided",
    INVALID_CATEGORIES: "Invalid categories. Allowed are: Residential, Villas, Commercial",
    INVALID_SERVICES: "Invalid services. Allowed are: Architecture, Interior Design, Renovation",
    APPROVE_REQUIRED: "companyId and approve are required",
    SEARCH_SUCCESS: "Companies searched successfully",
    VERIFICATION_PENDING: "Company verification is pending approval by admin. Please wait.",
    DOCUMENTS_REJECTED: "Documents rejected. Please upload again.",
    SUBSCRIPTION_REQUIRED: "Active subscription required to configure slots.",
    SUBSCRIPTION_EXPIRED: "Subscription expired. Please renew to manage slots.",
    ACTIVE_RULE_ONLY_EXCEPTIONS:
      "Only exceptional days (holidays) can be modified for an active rule. Date range and schedule fields are locked until the rule ends.",
    SLOT_RULES_MAX: "You can have at most 3 slot rules. Remove or shorten a rule before adding another.",
    SLOT_RULE_DATE_OVERLAP: "This date range overlaps another slot rule. Rules cannot share overlapping dates.",
    EXCEPTIONAL_DAY_NOT_ON_AVAILABLE_WEEKDAY: (day: string) =>
      `Exceptional day falls on ${day}, which is not an available weekday in this rule. Only add holidays on days you already offer slots.`,
    EXCEPTIONAL_DAY_INVALID: "One or more exceptional days are invalid.",
    START_DATE_PAST: "Start date cannot be in the past.",
    END_DATE_INVALID: "End date must be after start date.",
    END_TIME_INVALID: "End time must be after start time.",
    SLOT_DURATION_INVALID: "Slot duration must be greater than 0.",
    BUFFER_TIME_NEGATIVE: "Buffer time cannot be negative.",
    SLOT_DURATION_BUFFER_EXCEEDS_TOTAL:
      "Slot duration + buffer time cannot exceed total available time.",
    WEEKDAY_REQUIRED: "At least one weekday must be selected.",
    INVALID_WEEKDAY: (day: string) => `Invalid weekday: ${day}`,
    EXCEPTIONAL_DAY_OUTSIDE_RANGE: (date: string) =>
      `Exceptional day ${date} is outside the configured date range.`,
    EDITING_LIMIT_REACHED: (date: string, count: number) =>
      `Editing is not possible: ${date} already has ${count} bookings (limit is 5).`,
    BOOKING_ALREADY_CANCELLED: "Booking is already cancelled.",
    BOOKING_CANCEL_WINDOW_EXCEEDED:
      "Bookings can only be cancelled within 24 hours of creation.",
    BOOKING_CANCEL_FAILED: "Failed to cancel booking.",
    BOOKING_CANCELLED_STATE_INVALID: "Cannot reschedule a cancelled booking.",
    SLOT_ALREADY_BOOKED: "This slot is already booked.",
    BUSINESS_SUSPENDED: "This business account has been suspended.",
    PLAN_NOT_FOUND: "Subscription plan not found",
    PLAN_NOT_ACTIVE: "Subscription plan is not active",
    BOOKING_CONFIRM_STATUS_INVALID: (status: string) =>
      `Cannot confirm booking with status: ${status}`,
    BOOKING_STATUS_UPDATE_FAILED: "Failed to update booking status",
    COMPANY_NOT_FOUND_WITH_EMAIL: "Company not found with this email",
  },

  ADMIN: {
    BLOCK_REQUIRED: "id and isBlocked are required",
    USER_BLOCK_SUCCESS: "User blocked successfully",
    USER_UNBLOCK_SUCCESS: "User unblocked successfully",
    COMPANY_BLOCK_SUCCESS: "Company blocked successfully",
    COMPANY_UNBLOCK_SUCCESS: "Company unblocked successfully",
    APPROVE_SUCCESS: "Company approved successfully",
    REJECT_SUCCESS: "Company rejected successfully",
  },

  CHAT: {
    CONVERSATION_PARTICIPANTS_REQUIRED: "Conversation must have exactly 2 participants",
    PARTICIPANT_ID_REQUIRED: "Participant participantId is required",
    PARTICIPANT_TYPE_REQUIRED: "Participant participantType is required",
    INVALID_PARTICIPANT_TYPE: "Participant has invalid participantType",
    DUPLICATE_PARTICIPANTS: "Cannot create conversation with same participant twice",
    MESSAGE_FETCH_SUCCESS: "Messages fetched successfully",
    CONVERSATION_FETCH_SUCCESS: "Conversations fetched successfully",
    ATTACHMENT_UPLOAD_SUCCESS: "Attachment uploaded successfully",
    SENDER_RECEIVER_SAME: "Cannot send message to yourself",
    MISSING_FIELDS: "Missing required message fields",
    UPLOAD_FAILED: "Upload failed",
    SENDER_TYPE_REQUIRED: "Sender participantType is required",
    RECEIVER_TYPE_REQUIRED: "Receiver participantType is required",
    INVALID_SENDER_TYPE: "Invalid sender participantType. Must be 'user' or 'company'",
    INVALID_RECEIVER_TYPE: "Invalid receiver participantType. Must be 'user' or 'company'",
  },

  REVIEW: {
    SUBMIT_SUCCESS: "Review submitted successfully",
    FETCH_SUCCESS: "Reviews fetched successfully",
    ALREADY_REVIEWED: "You have already reviewed this company",
  },

  SLOT: {
    CONFIG_SET_SUCCESS: "Slot configuration set successfully",
    CONFIG_FETCH_SUCCESS: "Slot configuration fetched successfully",
    CONFIG_DELETE_SUCCESS: "Slot configuration deleted successfully",
    AVAILABLE_FETCH_SUCCESS: "Available slots fetched successfully",
    SLOT_BOOKED_SUCCESS: "Slot booked successfully",
    ID_DATE_REQUIRED: "companyId and date are required",
    SLOT_ALREADY_TAKEN: "This slot has already been taken by someone else.",
    CONFIG_NOT_FOUND: "No slot rule applies for this company on the selected date.",
    RULE_NOT_FOUND: "Slot rule not found.",
    RULE_ID_REQUIRED: "Query parameter ruleId is required to delete a slot rule.",
    SLOT_PASSED_TODAY: "This time slot has already passed for today.",
    PAST_SLOT_BOOKING: "Cannot book slots in the past.",
    SLOT_PAYMENT_IN_PROGRESS: "Someone else is currently finishing their booking for this slot. Please wait a few minutes or choose another.",
  },

  BOOKING: {
    FETCH_SUCCESS: "Bookings fetched successfully",
    COMPLETE_SUCCESS: "Booking completed successfully",
    RESCHEDULE_SUCCESS: "Booking rescheduled successfully",
    NOT_FOUND: "Booking not found",
    UNAUTHORIZED: "You are not authorized to perform this action",
    SLOT_CONFLICT: "This slot was just taken by someone else who paid first.",
    BOOKING_CANCELLED_REFUND: "This slot was just taken by someone else. We will process your refund.",
    SERVICE_ALREADY_COMPLETED: "Service already marked as completed",
    BOOKING_NOT_PAID: "Cannot complete a booking that hasn't been paid for",
    BOOKING_ALREADY_CONFIRMED: "Booking already confirmed.",
    BOOKING_CANCELLED: "Booking cancelled successfully",
    REFUND_PROCESSED: "Refund processed successfully",
    CONFIRMED_SUCCESS: "Booking confirmed successfully!",
  },

  NOTIFICATION: {
    FETCH_SUCCESS: "Notifications fetched successfully",
    MARK_READ_SUCCESS: "Notification marked as read",
    MARK_ALL_READ_SUCCESS: "All notifications marked as read",
    NEW_REVIEW_TITLE: "New Review Received",
    NEW_REVIEW_MESSAGE: "A user has submitted a {rating}-star review for your service.",
    BOOKING_COMPLETED_TITLE: "Booking Completed",
    BOOKING_COMPLETED_MESSAGE: "User has marked the booking for {date} as completed. Settlement of {amount} initiated.",
  },

  GENERIC: {
    UNKNOWN_ERROR: "Something went wrong",
    BAD_REQUEST: "Invalid request",
    INTERNAL_ERROR: "An unexpected error occurred",
    UNAUTHORIZED: "Unauthorized",
    SERVER_ERROR: "Internal server error",
    SESSION_ID_REQUIRED: "Session ID is required",
    WEBHOOK_ERROR: "Webhook Error",
    REFUND_INITIATED: "Refund initiated successfully",
    PAYMENT_NOT_COMPLETED: "Payment not completed or session not found",
    SUBSCRIPTION_ACTIVATED: "Subscription activated",
  },

  VALIDATION: {
    ID_REQUIRED: "ID is required",
    REQUIRED_FIELDS_MISSING: "Required fields are missing",
    EMAIL_REQUIRED: "Email is required to identify the company",
  },

  // Use Case Response Messages
  RESPONSE: {
    USER_REGISTERED: (role: string) => `${role || "User"} registered successfully`,
  }
};
